### ISSUE TITLE
table rendering

### ISSUE THREAD

**Issue by petrasovaa** [veroandreo/grass_ncsu_2023#3]
Not sure whether to change this, but so that I don't forget about it I created this issue:

The knitr table is not rendering unless I use this:
```
library(IRdisplay)
display_html(toString(knitr::kable(th_maxent, format = 'html', digits = 2)))
```

**Comment by veroandreo** [comment]
Are you running it from a jupyter notebook? As I did all of it in Rstudio, I didn't get that issue. The only notebook I ran in jupyter was the one with grass commands since from Rstudio I didn't get the maps rendered... Perhaps the same reason but the other way around?

**Comment by petrasovaa** [comment]
Let's not worry about this. Given some other issues it will be best to run the R portion in rstudio.
